server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://eurekaserver:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service

          predicates:
            - Path=/organization/**

          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}

        - id: licensing-service-example
          uri: lb://licensing-service

          predicates:
            - Path=/licensing/**

          filters:
            - RewritePath=/licensing/(?<path>.*), /$\{path}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"